default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123456tA.
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: fpt_shop


test:
  <<: *default
  database: fpt_shop_test
